### ISSUE TITLE
No module named 'benchmark'

### ISSUE THREAD

**Issue by miniskar** [deephyper/benchmark#30]
Hi,
I have installed deephyper/benchmark using pip install. 
I am trying to load DTLZ for multi-objective optimization example of deephyper. However, I am getting below error.

```
$ python3 dtlz.py
2024-08-14 11:59:59,596 - INFO - core.py:load - Loading DTLZ
Traceback (most recent call last):
  File "/scratch/nqx/hunter.sep30/deffe/dtlz.py", line 19, in <module>
    dhb.load("DTLZ")
  File "/home/nqx/deffe/deffeenv/lib/python3.10/site-packages/deephyper_benchmark/core.py", line 72, in load
    benchmark = find_benchmark(name)
  File "/home/nqx/deffe/deffeenv/lib/python3.10/site-packages/deephyper_benchmark/core.py", line 27, in find_benchmark
    benchmark_module = importlib.import_module("benchmark")
  File "/scratch/nqx/spack/opt/spack/linux-centos8-zen/gcc-8.5.0/python-3.10.12-m4h7qefbpqayoqndxthi7ud7nc3a2uf5/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'benchmark'
```

With Regards,
Narasinga (ORNL)

**Comment by Deathn0t** [comment]
I also noticed that you are running the command from a location which has a local module name `dtlz` when `dhb.load("DTLZ")` will also look for a module named `dtlz`. Try renaming your `dtlz.py` script into `dtlz_benchmark_test.py` and run again.
